version: '2'

services:
  sonarqube:
    build: 
      context: sonarqube
#      args:
#        http_proxy: http://127.0.0.1:8080
    environment:
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=sonar
      - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonar
    ports:
      - 9000:9000
      - 9002:9002
    depends_on:
      - db
#    command:
#      -Dhttp.proxyHost=127.0.0.1 -Dhttp.proxyPort=8080

  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=sonar
      - POSTGRES_USER=sonar
    ports:
      - 5432:5432
    volumes:
      - sonarqube_postgresql_data:/var/lib/postgresql/data
# using the following line will result in the errors described on https://forums.docker.com/t/data-directory-var-lib-postgresql-data-pgdata-has-wrong-ownership/17963/24
#      - C:\Users\bellinsalarin\SonarQubeDatabase:/var/lib/postgresql/data

#networks:
#  sonarnet:
#    driver: bridge

# create the volume 
# docker volume create --name sonarqube_postgresql_data -d local
volumes:
  sonarqube_postgresql_data:
    external: true